import React from "react";

export const metadata = {
  title: "About || test test ",
  description: "Generated by create next app",
};

const page = () => {
  return <section>
    <div className="container-fluid custom_fluid">
      <h1>Hello There!</h1>
    </div>
  </section>;
};

export default page;
