export const aboutData = [
  "about-our-company",
  "automatic-door-supply-near-me",
  "our-portfolio",
  "customer-reviews",
  "resources",
];

export const services = [
  "door-design",
  "door-fabrication",
  "automatic-doors-installation",
  "automatic-door-repair",
  "hospital-automatic-doors",
  "commercial-automatic-doors",
  "residential-building-automatic-doors",
  "ada-door-operator",
  "interior-automatic-doors",
  "airports-automatic-doors",
  "school-automatic-doors",
  "church-temple-automatic-doors",
  "heavy-traffic-automatic-doors",
  "storefront-automatic-doors",
  "custom-automatic-doors",
];

export const serviceAreaData = [
  "nationwide-automatic-door-supply",
  "new-york-automatic-door-supply",
  "new-jersey-automatic-door-supply",
  "connecticut-automatic-door-supply",
  "philadelphia-automatic-door-supply",
  "tri-state-automatic-door-supply",
  "california-automatic-door-supply",
  "Texas-automatic-door-supply",
  "Florida-automatic-door-supply",
  "Ohio-automatic-door-supply",
  "Alaska-automatic-door-supply",
  "Hawaii-automatic-door-supply",
  "Georgia-automatic-door-supply",
  "Massachusetts-automatic-door-supply",
  "Washington-automatic-door-supply",
  "Virginia-automatic-door-supply",
  "Pennsylvania-automatic-door-supply",
  "Arizona-automatic-door-supply",
  "Michigan-automatic-door-supply",
  "North Carolina-automatic-door-supply",
  "Colorado-automatic-door-supply",
  "Tennessee-automatic-door-supply",
  "Illinois-automatic-door-supply",
  "Utah-automatic-door-supply",
];
