import localFont from "next/font/local";
import "@/assets/globals.scss";
// import BootstrapScript from "@/utils/BootstrapScript";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
export const metadata = {
  title: "Helllo || test test ",
  description: "Generated by create next app",
};

const pdfPro = localFont({
  src: [
    {
      path: "../font/pfdindisplaypro-regular-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/pfdindisplaypro-bold-webfont.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pdfPro.className}>
        <Navbar />
        <main>{children}</main>
        <Footer />
        {/* <BootstrapScript /> */}
      </body>
    </html>
  );
}
